steps:
- name: 'PRNUMBER'
  args: ['echo', '  #############  hello ${_PR_NUMBER}  #############']
- name: 'HEADBRAN'
  args: ['echo', '  #############  hello ${_BASE_BRANCH}  #############']

- name: 'SDSD'
  args: ['echo', '  #############  hello ${_HEAD_REPO_URL}  #############']

- name: ''
  args: ['echo', '  #############  hello ${_HEAD_BRANCH}  #############']
