steps:
- name: 'test'
  args: ['echo', '  #############  hello ${_PR_NUMBER}  #############']
- name: 'test1'
  args: ['echo', '  #############  hello ${_BASE_BRANCH}  #############']

- name: 'test2'
  args: ['echo', '  #############  hello ${_HEAD_REPO_URL}  #############']

- name: 'test3'
  args: ['echo', '  #############  hello ${_HEAD_BRANCH}  #############']
