steps:
- name: 'ubuntu'
  args: ['touch', 'new.txt hello.json new2.txt hello2.jsonnew5.txt hello5.json']

- name: 'ubuntu'
  enterypoint: /bin/bash
  args: ['pwd']
    #artifacts:
    #objects:
    #location: 'gs://playground-s-11-cf59b6e1'
    #paths: ['./*.txt','./*.json']
