steps:
- name: 'ubuntu'
  args: ['echo', '  #############  hello ${_PR_NUMBER}  #############']
- name: 'ubuntu'
  args: ['echo', '  #############  hello ${_BASE_BRANCH}  #############']

- name: 'ubuntu'
  args: ['echo', '  #############  hello ${_HEAD_REPO_URL}  #############']

- name: 'ubuntu'
  args: ['echo', '  #############  hello ${_HEAD_BRANCH}  #############']
