options:
  env:
    - PROJECT_ID=$PROJECT_ID
    
    
    
substitutions:
  _BRA: "HELLO substitutions"


steps:
- name: 'ubuntu'
  args: ['echo', '  #############  hello ${_PR_NUMBER}  #############']
- name: 'alpine'
  entrypoint: sh
  args:
    - -c
    - |
        chmod +x new.sh
        sh new.sh
