steps:
- name: 'ubuntu'
  args: ['echo', '#############hello ${_PRNUMBER}#############']
options:
    substitution_option: 'ALLOW_LOOSE'
    env:
      - PR_NUMBER=$_PRNUMBER
substitutions:
  _PRNUMBER: $(body.number)
